# Generated by Django 4.0 on 2022-01-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='motos'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
