# Generated by Django 4.0 on 2022-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_motos_imagen_propietario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
    ]
