# Generated by Django 4.0 on 2022-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_motos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen'),
        ),
    ]
