# Generated by Django 4.0 on 2022-02-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_motos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motos',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagen'),
            preserve_default=False,
        ),
    ]
