# Generated by Django 4.0 on 2022-02-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_motos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='motos'),
        ),
    ]
